### PR TITLE
Fixes table filters

### LINKED ISSUE #286: "Status" filter on index page
The javascript is not working when changing filters.

### PR DESCRIPTION
**Pull request by jemisonf**
Fix #286

### CODE REVIEW

File: app/javascript/packs/home_table_filters.js [hunk 1]
```diff
@@ -1,25 +1,42 @@
 // return true if array2 is a subset of array1. Both must be Javascript arrays. Ignores 'hidden' class in second array
 isSubset = function(array1, array2) {
   for (var i = 0; i < array2.length; i++) {
```
Comment (revgum) [inline app/javascript/packs/home_table_filters.js]: `isSubset` in javascript could be implemented using javascript `some`.. such as the following filter and some which should filter out the "hidden" and return true if array1 includes any of filtered elements

`array2.filter(e => e !== 'hidden').some((e, i, a) => array1.includes(e))`

Comment (revgum) [reply app/javascript/packs/home_table_filters.js]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some
